MAX_LENGTH: int = 100
STARTING_RADIUS: float = 75

SPEED_CONSTANT: float = 5
BOOST_SPEED_CONSTANT: float = 110 * SPEED_CONSTANT

MAX_TURN: float = 2
BOOST_TURN: float = 12

MIN_BOOST_RADIUS: float = 25

BOOST_SHRINK_RATE: float = 5
SHRINK_RATE_MULTIPLIER: float = 0.005

BOOST_DROP_RATE: float = 0.5

MASS_TO_RADIUS: float = 0.2

OPTIMAL_RESOLUTION_WIDTH = 1920

INITIAL_FOOD_SPAWN = 5000
SPAWN_FOOD_AREA = 1000
FOOD_DO_SOMETHING_EVERY = 10

FOOD_MAX_MASS = 20
DEATH_DROP_RATE = 0.075
DEATH_MASS_RANGE = [1, 20]

INSTRUCTIONS = """ WASD to MOVE\n SPACE to BOOST\n ESC to GO TO MENU"""
IS_DEBUG = False
