MAX_LENGTH: int = 100
SPEED_CONSTANT: float = 10
BOOST_SPEED_CONSTANT: float = 110 * SPEED_CONSTANT
MAX_TURN: float = 3
BOOST_TURN: float = 12
MIN_BOOST_RADIUS: float = 50
BOOST_SHRINK_RATE: float = 2
MASS_TO_RADIUS: float = 0.2
OPTIMAL_RESOLUTION_WIDTH = 1920
INITIAL_FOOD_SPAWN = 5000
SPAWN_FOOD_AREA = 1000
FOOD_DO_SOMETHING_EVERY = 0.5
FOOD_MAX_MASS = 20

INSTRUCTIONS = """ WASD to MOVE\n SPACE to BOOST\n ESC to GO TO MENU"""
IS_DEBUG = False

