MAX_LENGTH: int = 100
SPEED_CONSTANT: float = 10
BOOST_SPEED_CONSTANT: float = 110 * SPEED_CONSTANT
MAX_TURN: float = 0.05
BOOST_TURN: float = 0.2
MIN_BOOST_MASS: float = 50
MASS_TO_RADIUS: float = 0.1
OPTIMAL_RESOLUTION_WIDTH = 1920
